version: "3.9"
services:
  db:
    image: bitnami/postgresql
    #image: bitnami/postgresql:9.6.24
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  app:
    build: .
    command: bash prepare.sh
    container_name: bot
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
     - PORT=5432
     - HOST=db
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ./cron_task:/etc/cron.d/cron_task
    depends_on:
      - db